{% set name = "google-cloud-recommendations-ai" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-recommendations-ai-{{ version }}.tar.gz
  sha256: 92743dfcc1ad0f90d98338f0a6be973652d379078de2aaa01669dfbc79df0f67

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core >=1.26.0,<3.0.0dev
    - packaging >=14.3
    - proto-plus >=1.15.0

test:
  imports:
    - google
    - google.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-recommendations-ai
  license: Apache-2.0
  license_file: LICENSE
  summary: Python Client for Recommendations AI
  description: |
    Cloud Recommendations AI API: Deliver highly personalized product
    recommendations at scale.
  dev_url: https://github.com/googleapis/python-recommendations-ai
  doc_url: https://googleapis.dev/python/recommendationengine/latest/index.html

extra:
  recipe-maintainers:
    - xylar
